config/routes.rb
Radio::Application.routes.draw do
  resources :venues
  resources :artists

  root :to => "events#index"

  match 'artists/:id/songs' => 'artists#songs', :as => :artist_songs

  match 'events/today' => 'events#index', :as => :todays_events, 
                                          :defaults => {:when => 'today'}
  match 'events/this/:when' => 'events#index', :as => :events_by_date
  match 'events/service' => 'events#service'

  resources :events

  match 'contact' =>  'static#contact', :as => :contact

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates_presence_of :name

  has_and_belongs_to_many :events
  has_many :songs
  has_and_belongs_to_many :tags

  accepts_nested_attributes_for :songs

  def to_param
    "#{id}-#{name.downcase.gsub(/[^a-z0-9']+/i, '-')}"
  end

  def get_song
    songs.first
  end

  def to_s
    "Artist<#{name}>"
  end

  def self.get_artists(tags)
    return Artist.joins(:tags).where('tags.name IN (?)', tags)
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  respond_to :html, :json

  def index
    @artists = Artist.all(:order => :name)
    respond_with(@artists)
  end

  def show
    @artist = Artist.find(params[:id])
    @events = Event.get_upcoming_events(nil, [], nil, @artist.id)

    respond_to do |format|
      format.html { respond_with(@artist) }
      format.json { render :json => @artist.to_json(:include => :songs) }
    end
  end

  def edit
    @artist = Artist.find(params[:id])
    respond_with(@artist)
  end

  def update
    @artist = Artist.find(params[:id])
    new_song = params[:new_song]
    @artist.songs.create({:url => new_song}) if new_song
    if @artist.update_attributes(params[:artist]) or new_song
        redirect_to(@artist, :notice => 'Artist was successfully updated.')
    else
        render :action => "edit"
    end
  end

end

app/views/artists/edit.html.haml
-#
-# This module contains the edit artist template.
-#


= form_for(@artist, :url => {:action => :update}) do |f|
  - if @artist.errors.any?
    #error_explanation
      %h2
        #{pluralize(@artist.errors.count, "error")} prohibited this artist from being saved:

      %ul
      - @artist.errors.full_messages.each do |msg|
        %li #{msg}


  = f.fields_for :songs do |sf|
    .field
      = sf.label :url
      .br/
      = sf.text_field :url 

  %input(name="new_song")

  .actions
    = f.submit

app/views/artists/index.html.haml
%h1 Artists

#artists
- @artists.each do |artist|
  %li.artist
    = link_to artist.name, artist, :class=>"name"

%p= link_to 'New artist', new_artist_path

app/views/artists/show.html.haml
-#
-# This module contains the view artist template.
-# 

#artist
  #name= @artist.name

= render(:partial => "events/events", :locals => { :events => @events, :tags => [], :active_tags => []})